# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
 - cd tests
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python -m unittest discover; fi
after_success:
  coveralls